GAME_INFO_OFFSET_Y = 50
GAME_TIME_LIMIT_SECONDS = 180
GAME_OVER_SECONDS = 5
GAME_NAME = "Fruit Harvest"
GAME_WIDTH = 1024
GAME_HEIGHT = 768 + GAME_INFO_OFFSET_Y
GAME_TIME_FORMAT = "%M:%S"
GAME_FRUIT_TYPES_NEW = { ["apple"] = 3, ["orange"] = 5, ["banana"] = 10 }
GAME_FRUIT_SIDE_LENGTH = 40
GAME_FENCE_BUFFER = 5